version: '3'

services:

  node:
    image: thecodingmachine/nodejs:10
    volumes:
      - ./:/usr/src/app
    environment:
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: npm start
    ports:
      - "3000:3000"
