version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongodbclient:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000

  node:
    image: thecodingmachine/nodejs:14
    volumes:
      - ./:/usr/src/app
    environment:
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: nodemon ./bin/www
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 8080:8080

volumes:
  mongodb_data_container:

